export const DATABASE_COLLECTION_NAMES = {
	CRM: {
		ACTIVITIES: "activities",
		CLIENTS: "clients",
		CONECTA_SESSIONS: "conecta-sessions",
		CONECTA_INDICATIONS: "conecta-indications",
		CONECTA_VERIFICATION_TOKENS: "conecta-verification-tokens",
		CONECTA_CREDIT_REDEMPTION_REQUESTS: "conecta-credit-redemption-requests",
		CONECTA_INVITES: "conecta-invites",
		DISTANCES: "distances",
		EXPENSES: "expenses",
		FILE_REFERENCES: "file-references",
		FUNNEL_REFERENCES: "funnel-references",
		FUNNELS: "funnels",
		PROPOSALS: "proposals",
		PLANS: "signature-plans",
		SERVICES: "services",
		PROJECT_TYPES: "project-types",
		HOMOLOGATIONS: "homologations",
		INTEGRATIONS: "integrations",
		KITS: "kits",
		NOTIFICATIONS: "notifications",
		OPPORTUNITIES: "opportunities",
		OPPORTUNITIES_HISTORY: "opportunities-history",
		PARTNERS: "partners",
		PAYMENT_METHODS: "payment-methods",
		PRICING_METHODS: "pricing-methods",
		PROCESS_FLOW_REFERENCES: "process-flow-references",
		PROCESS_FLOW: "process-flows",
		PRODUCTS: "products",
		USERS: "users",
	},
};
